// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMfGb5uQFD7BnAx7qN2eeq99UaSR0sZOk',
    appId: '1:689622316584:web:8e8a91f02c009faf4ee71d',
    messagingSenderId: '689622316584',
    projectId: 'apartment-management-4996a',
    authDomain: 'apartment-management-4996a.firebaseapp.com',
    storageBucket: 'apartment-management-4996a.firebasestorage.app',
    measurementId: 'G-TR9ZD5XGHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoyZ1M01OgGunXeowblZO1WAfB0F8Jb0U',
    appId: '1:689622316584:android:9e7514338fb5a22b4ee71d',
    messagingSenderId: '689622316584',
    projectId: 'apartment-management-4996a',
    storageBucket: 'apartment-management-4996a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU5dbn0iAqiiv2R6_J9FnkyZ93wvHo98',
    appId: '1:689622316584:ios:a9feb84d5b9641764ee71d',
    messagingSenderId: '689622316584',
    projectId: 'apartment-management-4996a',
    storageBucket: 'apartment-management-4996a.firebasestorage.app',
    iosBundleId: 'com.example.apartmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANU5dbn0iAqiiv2R6_J9FnkyZ93wvHo98',
    appId: '1:689622316584:ios:a9feb84d5b9641764ee71d',
    messagingSenderId: '689622316584',
    projectId: 'apartment-management-4996a',
    storageBucket: 'apartment-management-4996a.firebasestorage.app',
    iosBundleId: 'com.example.apartmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMfGb5uQFD7BnAx7qN2eeq99UaSR0sZOk',
    appId: '1:689622316584:web:84a204b8b65308884ee71d',
    messagingSenderId: '689622316584',
    projectId: 'apartment-management-4996a',
    authDomain: 'apartment-management-4996a.firebaseapp.com',
    storageBucket: 'apartment-management-4996a.firebasestorage.app',
    measurementId: 'G-6BS11ZDRFX',
  );
}
